jewelry_shop/shop/urls.py
from django.urls import path

from jewelry_shop.shop.views import HomeView, DashboardView, DashboardNoProfileView, \
    ProductDetailsView, EditProductView, delete_product, CreateProductView, ShowAllProfiles, NotFoundView, product_list

urlpatterns = (
    path('', HomeView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('all-profiles/', ShowAllProfiles.as_view(), name='profiles'),

    path('dashboard-no-profile', DashboardNoProfileView.as_view(), name='dashboard with-out profile'),

    path('product-create/', CreateProductView.as_view(), name='create product'),
    path('product/edit/<int:pk>/', EditProductView.as_view(), name='edit product'),
    path('product/delete/<int:pk>/', delete_product, name='delete product'),
    path('product/details/<int:pk>/', ProductDetailsView.as_view(), name='product details'),

    path('product-list', product_list, name='product list'),
    path('not-found/', NotFoundView.as_view(), name='page not found')
)

jewelry_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('jewelry_shop.shop.urls')),
        path('profile/', include('jewelry_shop.accounts.urls')),
        path('cart/', include('jewelry_shop.shopping_cart.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelry_shop/shop/models.py
from django.db import models


class Product(models.Model):
    RING = "Ring"
    NECKLACE = "Necklace"
    CHAIN = "Chain"
    EARRINGS = "Earrings"
    # IMAGE_UPLOAD_TO_DIR = 'products/'

    TYPES = [(x, x) for x in (RING, NECKLACE, CHAIN, EARRINGS)]
    PRODUCT_NAME_MAX_LEN = 30

    name = models.CharField(
        max_length=PRODUCT_NAME_MAX_LEN,
        # null=False,
        # blank=False,
    )

    type = models.CharField(
        max_length=max(len(x) for (x, _) in TYPES),
        choices=TYPES,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image = models.ImageField(
        # upload_to=IMAGE_UPLOAD_TO_DIR,
        null=True,
        blank=True,
        default='no_image.png'
    )

    price = models.FloatField(
        null=False,
        blank=False,
    )

    def __str__(self):
        return f'{self.type} {self.price}'

jewelry_shop/shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from jewelry_shop.accounts.models import Profile
from jewelry_shop.shop.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(
        Product,
        on_delete=models.SET_NULL,
        null=True
    )

    is_ordered = models.BooleanField(
        default=False,
    )

    date_added = models.DateTimeField(
        auto_now=True,
    )

    date_ordered = models.DateTimeField(
        null=True,
    )

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(
        max_length=15,
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
    )

    is_ordered = models.BooleanField(
        default=False,
    )

    items = models.ManyToManyField(
        OrderItem,
    )

    date_ordered = models.DateTimeField(
        auto_now=True,
    )

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        # return '{0} - {1}'.format(self.owner, self.ref_code)
        return f'{self.owner}'

jewelry_shop/shop/forms.py
# from jewelry_shop.common.helpers import BootstrapFormMixin
from jewelry_shop.shop.models import Product  # Product
from django import forms


class DeleteProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['readonly'] = 'readonly'

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Product
        fields = ('name', 'type', 'price', 'image', 'description')


# class CreateProductForm(BootstrapFormMixin, forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self._init_bootstrap_form_controls()
#
#     RING = "Ring"
#     NECKLACE = "Necklace"
#     CHAIN = "Chain"
#     EARRINGS = "Earrings"
#     PRODUCT_NAME_MAX_LEN = 30
#     TYPES = [(x, x) for x in (RING, NECKLACE, CHAIN, EARRINGS)]
#
#     name = forms.CharField(
#         max_length=PRODUCT_NAME_MAX_LEN,
#         # null=False,
#         # blank=False,
#     )
#
#     type = forms.ChoiceField(
#         # max_length=max(len(x) for (x, _) in TYPES),
#         choices=TYPES,
#     )
#
#     description = forms.CharField(
#         widget={
#             forms.Textarea
#         }
#     )
#
#     image = forms.ImageField(
#         # upload_to=IMAGE_UPLOAD_TO_DIR,
#         null=True,
#         blank=True,
#         # default='no_image.png'
#     )
#
#     price = forms.FloatField(
#         null=False,
#         blank=False,
#     )
#
#     def save(self, commit=True):
#         product = Product(
#             name=self.cleaned_data['name'],
#             type=self.cleaned_data['type'],
#             description=self.cleaned_data['description'],
#             image=self.cleaned_data['image'],
#             price=self.cleaned_data['price'],
#         )
#
#         if commit:
#             return product.save()
#         return product
#
#     class Meta:
#         model = Product
#         fields = ('image', 'description', 'type', 'price', 'name')
#         widgets = {
#             'name': forms.TextInput(
#                 attrs={
#                     'placeholder': 'Enter product name',
#                 }
#             ),
#         }

jewelry_shop/shop/views.py
from django.contrib.auth import mixins as auth_mixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth.mixins import PermissionRequiredMixin
from jewelry_shop.accounts.models import Profile
from jewelry_shop.common.views_mixins import RedirectToDashboard, UserAccessMixin
from jewelry_shop.shop.forms import DeleteProductForm  # , CreateProductForm
from jewelry_shop.shop.models import Product
from jewelry_shop.shopping_cart.models import Order


class HomeView(RedirectToDashboard, views.TemplateView):
    template_name = 'shop/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hide_additional_nav_items'] = True
        return context


class DashboardView(views.ListView):
    model = Product
    template_name = 'shop/dashboard.html'
    context_object_name = 'products'


class DashboardNoProfileView(views.ListView):
    model = Product
    template_name = 'shop/dashboard_no_user.html'
    context_object_name = 'products'


class CreateProductView(auth_mixin.LoginRequiredMixin, UserAccessMixin, views.CreateView):
    permission_required = 'product.add_product'

    model = Product
    template_name = 'shop/product_create.html'
    fields = ('image', 'description', 'type', 'price', 'name')

    success_url = reverse_lazy('dashboard')

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)


class EditProductView(UserAccessMixin, views.UpdateView):
    permission_required = 'product.change_product'

    model = Product
    template_name = 'shop/photo_edit.html'
    fields = ('description', 'name', 'type', 'price')

    def get_success_url(self):
        return reverse_lazy('product details', kwargs={'pk': self.object.id})


def delete_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = DeleteProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = DeleteProductForm(instance=product)

    context = {
        'form': form,
        'product': product,
    }

    return render(request, 'shop/product_delete.html', context)


class ProductDetailsView(views.DetailView):  # auth_mixin.LoginRequiredMixin
    model = Product
    template_name = 'shop/product_details.html'
    context_object_name = 'product'

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)

        last_viewed_products = request.session.get('last_viewed_products_ids', [])

        last_viewed_products.insert(0, self.kwargs['pk'])
        request.session['last_viewed_products_ids'] = last_viewed_products[:3]

        return response


@login_required
def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, 'accounts/products_list.html', context)


class ShowAllProfiles(UserAccessMixin, auth_mixin.LoginRequiredMixin, views.ListView):
    permission_required = 'product.view_product'

    model = Profile
    template_name = 'shop/profiles.html'
    object = 'profile'


class NotFoundView(views.TemplateView):
    template_name = 'shop/404.html'

templates/shop/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h2 class='text-center'>
        {% if products %}
            Our Products
        {% else %}
            No products yet
        {% endif %}
    </h2>
    <div class="container mb-5">
        <div class="row mb-5">
            {% for product in products %}
                <div class="card ml-3 mb-3" style="width: 18rem;">
                    {% if not product.image %}
                        <p class="card-text">{% static 'images/pumpkin.jpg' %}</p>
                        <img src="/static/images/pumpkin.jpg" alt="error">
                    {% else %}
                        <img src="{{ product.image.url }}"
                             class="card-img-top" alt="Photo description">
                        <div class="card-body">
                    {% endif %}
                    <p class="card-text">{{ product.name }}</p>
                    {#                        <p class="card-text">{{ product.description }}</p>#}
                    <p class="card-text">{{ product.price|floatformat:2 }} lv.</p>
                    <a class="nav-link" href="{% url 'product details' product.id %}">View product</a>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <hr>

    {% if request.last_viewed_products_ids %}
        <h2>Last viewed products :</h2>

        <div class="container mb-5">
            <div class="row mb-5">

                {% for product in request.last_viewed_products_ids %}
                    <div class="card ml-3 mb-3" style="width: 18rem;">
                        {% if not product.image %}
                            <p class="card-text">{% static 'images/pumpkin.jpg' %}</p>
                        {% else %}
                            <img src="{{ product.image.url }}"
                                 class="card-img-top" alt="Photo description">
                            <div class="card-body">
                        {% endif %}
                        <p class="card-text">{{ product.name }}</p>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">{{ product.price }}</p>
                        <a class="nav-link" href="{% url 'product details' product.id %}">Product Details</a>


                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <hr>
    {% endif %}
{% endblock %}

templates/shop/dashboard_no_user.html
{% extends 'base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_one.css' %}">
    <title>Home</title>
</head>

{% block page_content %}
    <h2 class='text-center'>
        {% if not products %}
            No products yet
        {% endif %}
    </h2>

        <div class="container mb-5">
            <div class="row mb-5">
                {% for product in products %}
                    <div class="card ml-3 mb-3" style="width: 18rem;">
                            {% if not product.image %}
                                <p class="card-text">{% static 'images/pumpkin.jpg' %}</p>
                            {% else %}
                                <img src="{{ product.image.url }}"
                                     class="card-img-top" alt="Photo description">
                                <div class="card-body">
                            {% endif %}
                            <a class="nav-link" href="{% url 'product details' product.id %}">Product Details</a>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">{{ product.price|floatformat:2 }}</p>
                        <p class="card-text">{{ product.name }}</p>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

{#        <div class=" row d-flex justify-content-center align-content-center">#}
{#            <a href="{% url 'create product image' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add#}
{#                Photo</a>#}
{#        </div>#}

{% endblock %}

templates/shop/home_page.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}

    <div class="jumbotron">
{#        <img style="width: 100%"#}
{#        src="{% static 'images/pumpkin.jpg'  %}" alt="">          {# snimkata na home_page aka pri logvaneto #}
        <div class="position-sticky">
            <h1 class="display-4">Welcome to the CottonCandyShop</h1>
            <hr class="my-4">
            <div class="flex-row">

                <a href="{% url 'login user' %}" class="btn btn-lg btn-secondary">Login</a>
                <a href="{% url 'register user' %}" class="btn btn-lg btn-secondary">Register</a>

            </div>
        </div>
    </div>

{% endblock %}

templates/shop/photo_edit.html
{% extends 'base.html' %}
{% block page_content %}

    <h2 class="text-center">Edit Product Photo</h2>
    <img src="{{ object.image.url }}"
         class="w-50 rounded mx-auto d-block" alt="Photo description">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit product' object.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>

{% endblock %}

templates/shop/product_create.html
{% extends 'base.html' %}
{% block page_content %}

    <h1 class="text-center">Add Product Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'create product' %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>

{% endblock %}

templates/shop/product_delete.html
{% extends 'base.html' %}
{% block page_content %}

    <h2 class="text-center">Delete Product</h2>
    <div class="form">
        <form method="POST" action="{% url 'delete product' product.pk %} ">

            {{ form }}
            {%  csrf_token %}

            <input type="submit" value="Delete">
        </form>
    </div>

{% endblock %}

templates/shop/product_details.html
{% extends 'base.html' %}
{% block page_content %}

    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ product.image.url }}"
                 class="w-100 rounded mx-auto d-block" alt="{{ product.description }}"/>
        </div>
        <div class="d-inline p-2 w-50">
                <div class="d-flex justify-content-around">
                    <h5><u>Type:</u> {{ product.type }}</h5>      {# TUKA TRQBWA DA OPRAVQ DA IZLIZA KAKUW TIP E PRODUKTA!!!!!! #}
                </div>
            <p class="mt-2">{{ product.description }}</p>
            <p class="mt-2">{{ product.price|floatformat:2 }} lv.</p>

                    <a href="{% url 'add_to_cart' product.id %}">Add to Cart</a>

                {% if request.user.is_superuser or request.user.is_staff %}
                    <a class="nav-link" href="{% url 'edit product' product.id %}">Edit Product</a>
                    <a class="nav-link" href="{% url 'delete product' product.id %}">Delete Product</a>
                {% endif %}


        </div>
    </div>

{% endblock %}

templates/shop/profiles.html
{% extends 'base.html' %}
{% block page_content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <hr>

    {% for profile in profile_list %}
      <h2> {{ profile.first_name }} {{ profile.last_name }} ({{ profile.email }}),
        Has the following order: {{ profile.order_set }}
        With the given address: {{ profile.user.shippingaddress }} {# </h2> #}
        <hr>

             {% for order in orders %}
                {{ order }}
             {% endfor %}</h2>

    {% endfor %}
</body>
</html>

{% endblock %}